[mongo]
uri = "mongodb+srv://Garvit:YOUR_REAL_PASSWORD@store.bihf6uw.mongodb.net/?retryWrites=true&w=majority"
database = "retail_app"
collection_users = "users"
collection_products = "products"
