[mongo]
uri = "mongodb+srv://Garvit:bababro89@store.bihf6uw.mongodb.net/?appName=store"
database = "retail_app"
collection_users = "users"
collection_products = "products"
collection_sales = "sales"

